// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqxASKeBvRrObsyU7ut6sEy_q30Totqeo',
    appId: '1:988696334661:web:d43ad44cad0a0e17956e2c',
    messagingSenderId: '988696334661',
    projectId: 'ecommerceapp-9a4a7',
    authDomain: 'ecommerceapp-9a4a7.firebaseapp.com',
    storageBucket: 'ecommerceapp-9a4a7.appspot.com',
    measurementId: 'G-HLBCJGJ2CD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACLKSfe8FdMwlDetPTUGMNVsyWnvCjEYU',
    appId: '1:988696334661:android:179322d593d43197956e2c',
    messagingSenderId: '988696334661',
    projectId: 'ecommerceapp-9a4a7',
    storageBucket: 'ecommerceapp-9a4a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHd72TwJ7hvQpi3H80vQulAkTvDhe7GIc',
    appId: '1:988696334661:ios:61c1e90796cf69d3956e2c',
    messagingSenderId: '988696334661',
    projectId: 'ecommerceapp-9a4a7',
    storageBucket: 'ecommerceapp-9a4a7.appspot.com',
    androidClientId: '988696334661-g12cqdofm4memrbrp13njs5n8g43tv0h.apps.googleusercontent.com',
    iosClientId: '988696334661-htk2hd4m0vlq7d3g7tjtnqvcp48g8elj.apps.googleusercontent.com',
    iosBundleId: 'com.example.fashionForward',
  );
}
